jobs:
  build:
    working_directory: ~/ddd
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm install
      - run: node -v
      - run: npm -v
      - run: google-chrome --version
      - run: chromedriver -v


  test:
    docker:
      - image:  circleci/node:latest-browsers
    working_directory: ~/ddd
    steps:
      - checkout

      - run: npm run -script test1


      - store_artifacts:
          path: /home/circleci/ddd/node_modules/token-wizard-test-automation/results/



workflows:
       version: 2
       build_and_test:
         jobs:
           - build
           - test:
               requires:
                 - build